router-and-axios
dfcz3322/marvelproject pull request #2
Opened 2021-09-20 08:49 UTC by dfcz3322

2021-09-20 13:49 UTC, alinalaktionova requested changes

2021-09-20 13:49 UTC, alinalaktionova commented on public/index.html
> +<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
code style

2021-09-20 13:49 UTC, alinalaktionova commented on src/components/hero/hero.tsx
> +        <Grid
I think eslint has inappropriate config, cause code style is awful

2021-09-20 13:49 UTC, alinalaktionova commented on src/components/marvelButton/marvelButton.css
> +    border-right: 1px solid #fff;
you can concat this with border-left property

2021-09-20 13:49 UTC, alinalaktionova commented on src/components/marvelButton/marvelButton.css
> +    border-width: 0 0 16px 16px;
create a variable for the same properties to reduce duplication

2021-09-20 13:49 UTC, alinalaktionova commented on src/components/marvelButton/marvelButton.css
> +-45deg,#fff,#fff 1px,transparent 0,transparent 16px);
the same with code spacing

2021-09-20 13:49 UTC, alinalaktionova commented on src/components/marvelButton/marvelButton.css
> +.cta-btn .innerfill:after, .cta-btn .innerfill:before {
you have the same part of code above

2021-09-20 13:49 UTC, alinalaktionova commented on src/components/marvelButton/marvelButton.tsx
> +  margin?: string;
can't find usage of margin in your component

2021-09-20 13:49 UTC, alinalaktionova commented on src/intarface/interface.ts
> +export interface IComics {
so many repeatable properties in interfaces and some interfaces are exactly the same, rewrite them

2021-09-20 13:49 UTC, alinalaktionova commented on src/pages/search.tsx
> +      getComics() {
api requests should be located in the separate file

2021-09-20 13:49 UTC, alinalaktionova commented on src/pages/search.tsx
> +        axios.get("http://gateway.marvel.com/v1/public/characters", {
create baseUrl for axios requests

2021-09-20 13:49 UTC, alinalaktionova commented on src/pages/search.tsx
> +                apikey: "cffc6e60c4ebf25fdb0c2a3a87cfdc6f",
store api keys in .env variables, it's not secure to write them explicitly in code

2021-09-20 13:49 UTC, alinalaktionova commented on src/pages/search.tsx
> +                ...(this.state.searchQuery.length && {nameStartsWith: this.state.searchQuery})
create a variable for the expression to make it more clear

2021-09-20 13:49 UTC, alinalaktionova commented on src/pages/search.tsx
> +            search: `?search=${this.state.searchQuery}`
not a good way to pass state values here, you can have bugs with this approach. use method params to pass actual values

2021-09-20 13:49 UTC, alinalaktionova commented on src/pages/search.tsx
> +        this.setState({searchQuery: event.target.value});
you can change query string in lifecycle methods or in onChange handler

2021-09-22 14:43 UTC, dfcz3322 commented on src/components/marvelButton/marvelButton.css
> +    border-right: 1px solid #fff;
I cannot set them in a single statement: 
https://stackoverflow.com/questions/3126995/combining-border-top-border-right-border-left-border-bottom-in-css

2021-09-29 10:49 UTC, alinalaktionova requested changes

2021-09-29 10:49 UTC, alinalaktionova commented on .prettierrc.json
> +    "tabWidth": 4,
usually 2 is used

2021-09-29 10:49 UTC, alinalaktionova commented on .prettierrc.json
> +    "singleQuote": false,
singleQuote is better)) than double

2021-09-29 10:49 UTC, alinalaktionova commented on src/components/searchBar/searchBar.css
> +    color: white !important;
bad practice to use important

2021-09-29 10:49 UTC, alinalaktionova commented on src/components/searchLogo/searchLogo.tsx
> +                src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Marvel_Logo.svg/2560px-Marvel_Logo.svg.png"
create variable for this

2021-09-29 10:49 UTC, alinalaktionova commented on src/pages/comics.tsx
> +        handleRequest(`characters/${(this.props.match?.params as any).id}/comics`)
`characters/${(this.props.match?.params as any).id}/comics` not a good way to pass params that way

2021-09-29 10:49 UTC, alinalaktionova commented on src/pages/comics.tsx
> +                this.setState({ comics: response.data.data.results });
parse result data in api file and return end result to use it in react component

2021-09-29 10:49 UTC, alinalaktionova commented on src/pages/search.tsx
> +                {this.state.isLoading ? <LoadingOverlay></LoadingOverlay> : null}
no need to have closed tag if there is no body, just <LoadingOverlay/>

2021-10-08 13:06 UTC, alinalaktionova approved these changes

2021-10-08 13:22 UTC, merged