Implemented redux without saga
dfcz3322/marvelproject pull request #3
Opened 2021-10-08 13:23 UTC by dfcz3322

2021-10-11 09:52 UTC, alinalaktionova requested changes
your code style doesn't follow common js conventions. Edit spacing through the code and replace double quotes on single

2021-10-11 09:52 UTC, alinalaktionova commented on src/actions/comics.ts
> +        type: 'comics/setComics',
types should be constants and uppercased

2021-10-11 09:52 UTC, alinalaktionova commented on src/actions/comics.ts
> +import { IMarvelEntityResponse } from "../interface/interface";
no need to create separate file for one action

2021-10-11 09:52 UTC, alinalaktionova commented on src/reducer/comicsReducer.tsx
> +export const comics = (state: IComicsReduxState = initialComics, action: { type: string, payload: unknown }): IComicsReduxState => {
don't use type unknown

2021-10-11 09:52 UTC, alinalaktionova commented on src/reducer/searchReducer.tsx
> +        case 'search/setSearchQuery':
what is the point of storing search query in redux?

2021-10-11 09:52 UTC, alinalaktionova commented on src/pages/search.tsx
> +        handleRequest(`characters`, searchParam)
'' instead ``

2021-10-12 10:36 UTC, dfcz3322 commented on src/reducer/searchReducer.tsx
> +        case 'search/setSearchQuery':
this is in order to keep consistency as now characters are in redux store so I wanted to move as much as possible to redux store and not to mix component state and redux state. I can revert if it's incorrect

2021-10-12 15:14 UTC, alinalaktionova commented on src/reducer/searchReducer.tsx
> +        case 'search/setSearchQuery':
you can just past it as function argument and not store

2021-10-12 15:15 UTC, alinalaktionova reviewed
remove search query from redux

2021-10-18 13:42 UTC, alinalaktionova requested changes

2021-10-18 13:42 UTC, alinalaktionova commented on src/actions/search.ts
>  export const SET_CHARACTERS = 'SEARCH/SET_CHARACTERS';
just SET_CHARACTERS

2021-10-18 13:42 UTC, alinalaktionova commented on src/actions/search.ts
>  export const SET_SEARCH_QUERY = 'SEARCH/SET_SEARCH-QUERY';
I think it's redundant for now

2021-10-18 13:42 UTC, alinalaktionova commented on src/pages/search.tsx
> +      ...(query.length && {search: `?search=${query}`}),
not readable

2021-10-19 12:58 UTC, alinalaktionova approved these changes

2021-10-19 16:17 UTC, merged